plugins {
    id 'java'
    id 'application'
}

group = 'pokemon'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'pocketbattles.ui.BattleUI'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
